version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./server/API/.env:/app/.env 
    restart: always
    networks:
      - melodify-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - melodify-network
    depends_on:
      - server

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - melodify-network
    depends_on:
      - prometheus

networks:
  melodify-network:
    name: melodify-network
    driver: bridge
