version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    networks:
      - melodify-network

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    networks:
      - melodify-network

networks:
  melodify-network:
    driver: bridge
