name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install client dependencies
        run: npm install
        working-directory: ./client/client

      - name: Run client unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./client/client

      - name: Build client
        run: npm run build -- --configuration production
        working-directory: ./client/client

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker compose -f ./docker-compose.yml build
          docker compose -f ./docker-compose.yml push
